apiVersion: v1
kind: ServiceAccount
metadata:
  name: uaip-hub
  namespace: uaip
  labels:
    app: uaip-hub

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: uaip-hub
  namespace: uaip
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: uaip-hub
  namespace: uaip
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: uaip-hub
subjects:
  - kind: ServiceAccount
    name: uaip-hub
    namespace: uaip
